include("$(PORT_DIR)/boards/manifest.py")
freeze("$(BOARD_DIR)", ("pyg.py"))
freeze("$(PORT_DIR)/boards/NUCLEO_WB55", "rfcore_firmware.py")
freeze("$(BOARD_DIR)", ("ble_repl.py"))
freeze("$(MPY_DIR)/drivers/neopixel", ("neopixel.py"))
